// templates/react/tanstack-chat-ai/src/components/ChatPanel.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { useChat, fetchServerSentEvents } from "@tanstack/ai-react";
import { MessageList } from "./MessageList";
import { ChatInput } from "./ChatInput";
import { SettingsDrawer } from "./SettingsDrawer";
import { Sidebar } from "./Sidebar";
import {
  useConversationHistory,
  type SavedConversation,
} from "../hooks/useConversationHistory";
import type { Settings, Provider, AzionAuthType } from "../hooks/useSettings";

interface Props {
  settings: Settings & {
    setProvider: (p: Provider) => void;
    setModel: (m: string) => void;
    setApiKey: (k: string) => void;
    setAzionAuthType: (t: AzionAuthType) => void;
  };
  apiUrl?: string;
}

function newId() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
}

const SUGGESTIONS = [
  "Explique um conceito",
  "Escreva um código",
  "Resuma um texto",
  "Ajude-me a criar",
];

export function ChatPanel({ settings, apiUrl = "/api/chat" }: Props) {
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [currentConvId, setCurrentConvId] = useState("");

  useEffect(() => {
    setCurrentConvId(newId());
  }, []);
  const settingsRef = useRef(settings);
  settingsRef.current = settings;

  const history = useConversationHistory();

  const connection = useRef(
    fetchServerSentEvents(apiUrl, async () => ({
      headers: {
        "X-Api-Key": settingsRef.current.apiKey,
        "X-Provider": settingsRef.current.provider,
        "X-Model": settingsRef.current.model,
        "X-Azion-Auth-Type": settingsRef.current.azionAuthType,
      },
    })),
  ).current;

  const {
    messages,
    sendMessage,
    setMessages,
    isLoading,
    stop,
    reload,
    clear,
    error,
  } = useChat({ connection });

  const noKey = !settings.apiKey.trim();

  const displayMessages = useMemo(
    () => messages.filter((m) => m.role === "user" || m.role === "assistant"),
    [messages],
  );
  const hasMessages = displayMessages.length > 0;
  const lastIsAssistant =
    displayMessages[displayMessages.length - 1]?.role === "assistant";

  useEffect(() => {
    if (displayMessages.length > 0) {
      history.save(currentConvId, displayMessages);
    }
  }, [displayMessages, currentConvId]);

  function handleLoadConversation(conv: SavedConversation) {
    setMessages(conv.messages);
    setCurrentConvId(conv.id);
  }

  function handleNewConversation() {
    clear();
    setCurrentConvId(newId());
  }

  function handleSend(text: string) {
    sendMessage({ content: text });
  }

  return (
    <>
      <style>{`
        @keyframes fadeInChat {
          from { opacity: 0; transform: translateY(6px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        @keyframes fadeInEmpty {
          from { opacity: 0; }
          to   { opacity: 1; }
        }
      `}</style>

      <div
        style={{
          display: "flex",
          height: "100%",
          overflow: "hidden",
          background: "#111111",
        }}
      >
        <Sidebar
          isOpen={sidebarOpen}
          onToggle={() => setSidebarOpen((v) => !v)}
          conversations={history.conversations}
          currentId={currentConvId}
          onNewChat={handleNewConversation}
          onLoad={handleLoadConversation}
          onDelete={history.remove}
          onOpenSettings={() => setSettingsOpen(true)}
        />

        {/* Main area */}
        <div
          style={{
            flex: 1,
            display: "flex",
            flexDirection: "column",
            overflow: "hidden",
            minWidth: 0,
          }}
        >
          {!hasMessages ? (
            /* ── EMPTY STATE ── */
            <div
              style={{
                flex: 1,
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
                padding: "24px 20px 40px",
                position: "relative",
                animation: "fadeInEmpty 0.25s ease",
              }}
            >
              {/* Hamburger toggle when sidebar is closed */}
              {!sidebarOpen && (
                <button
                  onClick={() => setSidebarOpen(true)}
                  title="Abrir barra lateral"
                  style={{
                    position: "absolute",
                    top: "16px",
                    left: "16px",
                    width: "36px",
                    height: "36px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    background: "transparent",
                    border: "none",
                    borderRadius: "8px",
                    color: "#666666",
                    cursor: "pointer",
                    transition: "all 0.12s ease",
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.background = "rgba(255,255,255,0.08)";
                    e.currentTarget.style.color = "#FCFCFC";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.background = "transparent";
                    e.currentTarget.style.color = "#666666";
                  }}
                >
                  <HamburgerIcon />
                </button>
              )}

              <h1
                style={{
                  fontSize: "30px",
                  fontWeight: 600,
                  color: "#FCFCFC",
                  margin: "0 0 32px",
                  textAlign: "center",
                  letterSpacing: "-0.02em",
                  fontFamily: "'Sora', sans-serif",
                }}
              >
                No que você está pensando hoje?
              </h1>

              {/* Centered input */}
              <div style={{ width: "100%", maxWidth: "720px" }}>
                <ChatInput
                  onSend={handleSend}
                  onStop={stop}
                  isLoading={isLoading}
                  disabled={noKey}
                  disabledReason={
                    noKey
                      ? "Configure sua chave de API em Settings para começar"
                      : undefined
                  }
                />
              </div>

              {/* Suggestion chips */}
              <div
                style={{
                  display: "flex",
                  flexWrap: "wrap",
                  gap: "8px",
                  justifyContent: "center",
                  marginTop: "12px",
                }}
              >
                {SUGGESTIONS.map((s) => (
                  <button
                    key={s}
                    onClick={() => !noKey && handleSend(s)}
                    disabled={noKey}
                    style={{
                      padding: "8px 16px",
                      background: "rgba(255,255,255,0.05)",
                      border: "0.8px solid rgba(255,255,255,0.1)",
                      borderRadius: "999px",
                      color: noKey ? "#333333" : "#B2B2B2",
                      fontSize: "14px",
                      fontFamily: "'Sora', sans-serif",
                      cursor: noKey ? "not-allowed" : "pointer",
                      transition: "all 0.15s ease",
                    }}
                    onMouseEnter={(e) => {
                      if (!noKey) {
                        e.currentTarget.style.background =
                          "rgba(254,96,31,0.1)";
                        e.currentTarget.style.borderColor =
                          "rgba(254,96,31,0.3)";
                        e.currentTarget.style.color = "#FF8E4D";
                      }
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.background =
                        "rgba(255,255,255,0.05)";
                      e.currentTarget.style.borderColor =
                        "rgba(255,255,255,0.1)";
                      e.currentTarget.style.color = noKey
                        ? "#333333"
                        : "#B2B2B2";
                    }}
                  >
                    {s}
                  </button>
                ))}
              </div>

              {/* Settings shortcut */}
              {noKey && (
                <button
                  onClick={() => setSettingsOpen(true)}
                  style={{
                    marginTop: "20px",
                    display: "flex",
                    alignItems: "center",
                    gap: "6px",
                    background: "transparent",
                    border: "0.8px solid rgba(254,96,31,0.3)",
                    borderRadius: "6px",
                    color: "#FF8E4D",
                    fontSize: "12px",
                    fontFamily: "monospace",
                    letterSpacing: "0.05em",
                    cursor: "pointer",
                    padding: "6px 14px",
                    transition: "all 0.15s ease",
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.borderColor = "rgba(254,96,31,0.6)";
                    e.currentTarget.style.background = "rgba(254,96,31,0.08)";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.borderColor = "rgba(254,96,31,0.3)";
                    e.currentTarget.style.background = "transparent";
                  }}
                >
                  <GearIcon /> ABRIR SETTINGS
                </button>
              )}
            </div>
          ) : (
            /* ── ACTIVE STATE ── */
            <div
              style={{
                flex: 1,
                display: "flex",
                flexDirection: "column",
                overflow: "hidden",
                animation: "fadeInChat 0.25s ease",
              }}
            >
              {/* Thin header */}
              <header
                style={{
                  height: "52px",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  padding: "0 16px",
                  borderBottom: "0.8px solid rgba(255,255,255,0.06)",
                  flexShrink: 0,
                  background: "#111111",
                }}
              >
                <div
                  style={{ display: "flex", alignItems: "center", gap: "8px" }}
                >
                  {!sidebarOpen && (
                    <button
                      onClick={() => setSidebarOpen(true)}
                      title="Abrir barra lateral"
                      style={{
                        width: "32px",
                        height: "32px",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        background: "transparent",
                        border: "none",
                        borderRadius: "6px",
                        color: "#666666",
                        cursor: "pointer",
                        transition: "all 0.12s ease",
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background =
                          "rgba(255,255,255,0.08)";
                        e.currentTarget.style.color = "#FCFCFC";
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = "transparent";
                        e.currentTarget.style.color = "#666666";
                      }}
                    >
                      <HamburgerIcon />
                    </button>
                  )}
                  <span
                    style={{
                      fontSize: "14px",
                      fontWeight: 500,
                      color: "#666666",
                      fontFamily: "'Sora', sans-serif",
                    }}
                  >
                    {settings.provider === "openai" ? "OpenAI" : settings.provider === "anthropic" ? "Anthropic" : "Azion Copilot"}
                    {settings.provider !== "copilot-azion" && ` · ${settings.model}`}
                  </span>
                </div>

                <div
                  style={{ display: "flex", alignItems: "center", gap: "8px" }}
                >
                  <button
                    onClick={handleNewConversation}
                    title="Nova conversa"
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "5px",
                      background: "transparent",
                      border: "0.8px solid rgba(255,255,255,0.08)",
                      borderRadius: "6px",
                      color: "#666666",
                      fontSize: "12px",
                      fontFamily: "monospace",
                      letterSpacing: "0.04em",
                      cursor: "pointer",
                      padding: "5px 10px",
                      transition: "all 0.15s ease",
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.borderColor = "rgba(254,96,31,0.3)";
                      e.currentTarget.style.color = "#FF8E4D";
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.borderColor =
                        "rgba(255,255,255,0.08)";
                      e.currentTarget.style.color = "#666666";
                    }}
                  >
                    <ComposeSmallIcon /> NOVA
                  </button>
                  <button
                    onClick={() => setSettingsOpen(true)}
                    title="Configurações"
                    style={{
                      width: "32px",
                      height: "32px",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      background: "transparent",
                      border: "none",
                      borderRadius: "6px",
                      color: "#666666",
                      cursor: "pointer",
                      transition: "all 0.12s ease",
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.background =
                        "rgba(255,255,255,0.08)";
                      e.currentTarget.style.color = "#FCFCFC";
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.background = "transparent";
                      e.currentTarget.style.color = "#666666";
                    }}
                  >
                    <GearIcon />
                  </button>
                </div>
              </header>

              {/* Error banner */}
              {error && (
                <div
                  style={{
                    padding: "8px 24px",
                    background: "rgba(255,77,77,0.06)",
                    borderBottom: "0.8px solid rgba(255,77,77,0.2)",
                    display: "flex",
                    alignItems: "center",
                    gap: "8px",
                    flexShrink: 0,
                  }}
                >
                  <span style={{ color: "#FF4D4D", fontSize: "11px" }}>✕</span>
                  <span
                    style={{
                      fontFamily: "monospace",
                      fontSize: "11px",
                      color: "#FF8080",
                      letterSpacing: "0.03em",
                      flex: 1,
                    }}
                  >
                    {error.message}
                  </span>
                  {lastIsAssistant && !isLoading && (
                    <button
                      onClick={() => reload()}
                      style={{
                        background: "transparent",
                        border: "0.8px solid rgba(255,77,77,0.3)",
                        borderRadius: "4px",
                        color: "#FF4D4D",
                        fontSize: "10px",
                        fontFamily: "monospace",
                        letterSpacing: "0.06em",
                        cursor: "pointer",
                        padding: "3px 8px",
                      }}
                    >
                      RETRY
                    </button>
                  )}
                </div>
              )}

              <MessageList messages={displayMessages} isLoading={isLoading} />

              {/* Regenerate toolbar */}
              {!isLoading && !error && lastIsAssistant && (
                <div
                  style={{
                    padding: "6px 0",
                    display: "flex",
                    justifyContent: "center",
                    flexShrink: 0,
                  }}
                >
                  <button
                    onClick={() => reload()}
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "5px",
                      background: "transparent",
                      border: "0.8px solid rgba(255,255,255,0.08)",
                      borderRadius: "6px",
                      color: "#666666",
                      fontSize: "11px",
                      fontFamily: "monospace",
                      letterSpacing: "0.05em",
                      cursor: "pointer",
                      padding: "5px 12px",
                      transition: "all 0.15s ease",
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.borderColor = "rgba(254,96,31,0.3)";
                      e.currentTarget.style.color = "#FF8E4D";
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.borderColor =
                        "rgba(255,255,255,0.08)";
                      e.currentTarget.style.color = "#666666";
                    }}
                  >
                    <ReloadIcon /> REGENERAR
                  </button>
                </div>
              )}

              <ChatInput
                onSend={handleSend}
                onStop={stop}
                isLoading={isLoading}
                disabled={noKey}
                disabledReason={
                  noKey
                    ? "Configure sua chave de API em Settings para começar"
                    : undefined
                }
              />
            </div>
          )}
        </div>
      </div>

      <SettingsDrawer
        open={settingsOpen}
        onClose={() => setSettingsOpen(false)}
        settings={settings}
      />
    </>
  );
}

function HamburgerIcon() {
  return (
    <svg
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
    >
      <line x1="3" y1="6" x2="21" y2="6" />
      <line x1="3" y1="12" x2="21" y2="12" />
      <line x1="3" y1="18" x2="21" y2="18" />
    </svg>
  );
}

function GearIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="3" />
      <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z" />
    </svg>
  );
}

function ReloadIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor">
      <path
        fillRule="evenodd"
        d="M8 3a5 5 0 104.546 2.914.5.5 0 00-.908-.417A4 4 0 118 4V3z"
        clipRule="evenodd"
      />
      <path d="M8 4.466V.534a.25.25 0 00-.41-.192L5.23 2.308a.25.25 0 000 .384l2.36 1.966A.25.25 0 008 4.466z" />
    </svg>
  );
}

function ComposeSmallIcon() {
  return (
    <svg
      width="12"
      height="12"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20h9" />
      <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z" />
    </svg>
  );
}

// templates/vue/vue-chat-ai/components/ChatPanel.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useChat, fetchServerSentEvents } from '@tanstack/ai-vue'
import ChatInput from './ChatInput.vue'
import MessageList from './MessageList.vue'
import Sidebar from './Sidebar.vue'
import SettingsDrawer from './SettingsDrawer.vue'
import type { UseSettings } from '~/composables/useSettings'
import { useConversationHistory, type SavedConversation } from '~/composables/useConversationHistory'
import { useTheme } from '~/composables/useTheme'

const theme = useTheme()

const props = withDefaults(
  defineProps<{
    settings: UseSettings
    apiUrl?: string
  }>(),
  { apiUrl: '/api/chat' },
)

const SUGGESTIONS = [
  'Como criar uma Edge Application?',
  'Como escrever uma Edge Function?',
  'O que é o Azion WAF?',
  'Como configurar Cache Rules?',
]

function newId() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
}

const settingsOpen = ref(false)
const sidebarOpen = ref(true)
const currentConvId = ref('')

onMounted(() => {
  currentConvId.value = newId()
})

const history = useConversationHistory()

const connection = fetchServerSentEvents(props.apiUrl, async () => ({
  headers: {
    'X-Api-Key': props.settings.apiKey.value,
    'X-Provider': props.settings.provider.value,
    'X-Model': props.settings.model.value,
    'X-Azion-Auth-Type': props.settings.azionAuthType.value,
  },
}))

const { messages, sendMessage, setMessages, isLoading, stop, reload, clear, error } = useChat({ connection })

const noKey = computed(() => !props.settings.apiKey.value.trim())

const displayMessages = computed(() =>
  messages.value.filter((m) => m.role === 'user' || m.role === 'assistant'),
)
const hasMessages = computed(() => displayMessages.value.length > 0)
const lastIsAssistant = computed(
  () => displayMessages.value[displayMessages.value.length - 1]?.role === 'assistant',
)

watch(
  displayMessages,
  (msgs) => {
    if (msgs.length > 0) {
      history.save(currentConvId.value, msgs)
    }
  },
  { deep: true },
)

function handleLoadConversation(conv: SavedConversation) {
  setMessages(conv.messages)
  currentConvId.value = conv.id
}

function handleNewConversation() {
  clear()
  currentConvId.value = newId()
}

function handleSend(text: string) {
  sendMessage({ content: text })
}

function suggestionClick(s: string) {
  if (!noKey.value) handleSend(s)
}

const providerLabel = computed(() =>
  props.settings.provider.value === 'openai'
    ? 'OpenAI'
    : props.settings.provider.value === 'anthropic'
      ? 'Anthropic'
      : 'Azion Copilot',
)
</script>

<template>
  <div class="flex h-full overflow-hidden bg-[var(--bg-canvas)]">
    <Sidebar
      :is-open="sidebarOpen"
      :conversations="history.conversations.value"
      :current-id="currentConvId"
      @toggle="sidebarOpen = !sidebarOpen"
      @new-chat="handleNewConversation"
      @load="handleLoadConversation"
      @delete="history.remove"
      @open-settings="settingsOpen = true"
    />

    <!-- Main area -->
    <div class="flex-1 flex flex-col overflow-hidden min-w-0">
      <!-- EMPTY STATE -->
      <div
        v-if="!hasMessages"
        class="flex-1 flex flex-col items-center justify-center px-[var(--spacing-5)] pt-[var(--spacing-6)] pb-[var(--spacing-10)] relative"
        style="animation: fadeInEmpty 0.25s ease;"
      >
        <button
          v-if="!sidebarOpen"
          title="Abrir barra lateral"
          class="absolute top-[var(--spacing-4)] left-[var(--spacing-4)] w-9 h-9 flex items-center justify-center bg-transparent border-0 rounded-[var(--shape-button)] text-[var(--text-muted)] cursor-pointer transition-colors hover:bg-[var(--bg-hover)] hover:text-[var(--text-default)]"
          @click="sidebarOpen = true"
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">
            <line x1="3" y1="6" x2="21" y2="6" />
            <line x1="3" y1="12" x2="21" y2="12" />
            <line x1="3" y1="18" x2="21" y2="18" />
          </svg>
        </button>

        <button
          :title="theme.mode.value === 'dark' ? 'Modo claro' : 'Modo escuro'"
          class="absolute top-[var(--spacing-4)] right-[var(--spacing-4)] w-9 h-9 flex items-center justify-center bg-transparent border-0 rounded-[var(--shape-button)] text-[var(--text-muted)] cursor-pointer transition-colors hover:bg-[var(--bg-hover)] hover:text-[var(--text-default)]"
          @click="theme.toggle()"
        >
          <svg v-if="theme.mode.value === 'dark'" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="4" />
            <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41" />
          </svg>
          <svg v-else width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
          </svg>
        </button>

        <h1 class="text-heading-lg text-[var(--text-default)] m-0 mb-[var(--spacing-2)] text-center tracking-tight">
          Documentação Azion
        </h1>
        <p class="text-body-sm text-[var(--text-muted)] m-0 mb-[var(--spacing-2)] text-center max-w-[520px]">
          Respondo dúvidas sobre a documentação da Azion.
        </p>
        <a
          href="https://www.azion.com/en/documentation/"
          target="_blank"
          rel="noopener"
          class="text-body-xs text-[var(--primary)] hover:underline mb-[var(--spacing-6)] inline-flex items-center gap-[var(--spacing-1)]"
        >
          Ver documentação completa
          <svg width="12" height="12" viewBox="0 0 14 14" fill="currentColor" aria-hidden="true">
            <path d="M6.997.813a.53.53 0 0 1 0 1.061H2.755a.884.884 0 0 0-.884.884v8.484a.884.884 0 0 0 .884.884h8.484a.885.885 0 0 0 .884-.884V7a.53.53 0 0 1 1.06 0v4.242a1.946 1.946 0 0 1-1.944 1.944H2.755A1.945 1.945 0 0 1 .81 11.242V2.758A1.945 1.945 0 0 1 2.755.813h4.242Zm5.656 0c.04.001.077.006.115.015a.529.529 0 0 1 .416.703v2.64a.539.539 0 0 1-.53.531.538.538 0 0 1-.531-.53V2.647L8.411 6.293a.524.524 0 0 1-.353.177.53.53 0 0 1-.354-.884l3.712-3.712h-1.59a.53.53 0 0 1 0-1.06h2.827Z" />
          </svg>
        </a>

        <div class="w-full max-w-[720px]">
          <ChatInput
            :is-loading="isLoading"
            :disabled="noKey"
            :disabled-reason="noKey ? 'Configure sua chave de API em Settings para começar' : undefined"
            @send="handleSend"
            @stop="stop"
          />
        </div>

        <!-- Suggestions -->
        <div class="flex flex-wrap gap-[var(--spacing-2)] justify-center mt-[var(--spacing-3)]">
          <button
            v-for="s in SUGGESTIONS"
            :key="s"
            :disabled="noKey"
            class="suggestion-btn text-body-sm px-[var(--spacing-4)] py-[var(--spacing-2)] rounded-full transition-colors"
            :class="noKey
              ? 'bg-[var(--bg-hover)] border border-[var(--border-muted)] text-[var(--text-disabled)] cursor-not-allowed'
              : 'bg-[var(--bg-hover)] border border-[var(--border-muted)] text-[var(--text-default)] cursor-pointer hover:bg-[var(--primary-mask)] hover:border-[var(--primary)] hover:text-[var(--primary-contrast)]'"
            @click="suggestionClick(s)"
          >
            {{ s }}
          </button>
        </div>

        <!-- Settings shortcut -->
        <button
          v-if="noKey"
          class="mt-[var(--spacing-5)] flex items-center gap-[var(--spacing-1)] bg-transparent border border-[var(--primary)] rounded-[var(--shape-button)] text-[var(--primary-contrast)] text-body-xs font-mono tracking-wider cursor-pointer px-[var(--spacing-3)] py-[var(--spacing-1)] transition-colors hover:bg-[var(--primary-mask)]"
          @click="settingsOpen = true"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="3" />
            <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z" />
          </svg>
          ABRIR SETTINGS
        </button>
      </div>

      <!-- ACTIVE STATE -->
      <div
        v-else
        class="flex-1 flex flex-col overflow-hidden"
        style="animation: fadeInChat 0.25s ease;"
      >
        <!-- Thin header -->
        <header
          class="h-[52px] flex items-center justify-between px-[var(--spacing-4)] border-b border-[var(--border-muted)] flex-shrink-0 bg-[var(--bg-canvas)]"
        >
          <div class="flex items-center gap-[var(--spacing-2)]">
            <button
              v-if="!sidebarOpen"
              title="Abrir barra lateral"
              class="w-8 h-8 flex items-center justify-center bg-transparent border-0 rounded-[var(--shape-button)] text-[var(--text-muted)] cursor-pointer transition-colors hover:bg-[var(--bg-hover)] hover:text-[var(--text-default)]"
              @click="sidebarOpen = true"
            >
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">
                <line x1="3" y1="6" x2="21" y2="6" />
                <line x1="3" y1="12" x2="21" y2="12" />
                <line x1="3" y1="18" x2="21" y2="18" />
              </svg>
            </button>
            <span class="text-body-xs text-[var(--text-muted)]">
              Docs Assistant · {{ providerLabel }}<template v-if="settings.provider.value !== 'copilot-azion'"> · {{ settings.model.value }}</template>
            </span>
            <a
              href="https://www.azion.com/en/documentation/"
              target="_blank"
              rel="noopener"
              class="text-body-xs text-[var(--primary)] hover:underline hidden sm:inline-flex items-center gap-[var(--spacing-1)]"
            >
              Docs
              <svg width="10" height="10" viewBox="0 0 14 14" fill="currentColor" aria-hidden="true">
                <path d="M6.997.813a.53.53 0 0 1 0 1.061H2.755a.884.884 0 0 0-.884.884v8.484a.884.884 0 0 0 .884.884h8.484a.885.885 0 0 0 .884-.884V7a.53.53 0 0 1 1.06 0v4.242a1.946 1.946 0 0 1-1.944 1.944H2.755A1.945 1.945 0 0 1 .81 11.242V2.758A1.945 1.945 0 0 1 2.755.813h4.242Zm5.656 0c.04.001.077.006.115.015a.529.529 0 0 1 .416.703v2.64a.539.539 0 0 1-.53.531.538.538 0 0 1-.531-.53V2.647L8.411 6.293a.524.524 0 0 1-.353.177.53.53 0 0 1-.354-.884l3.712-3.712h-1.59a.53.53 0 0 1 0-1.06h2.827Z" />
              </svg>
            </a>
          </div>

          <div class="flex items-center gap-[var(--spacing-2)]">
            <button
              title="Nova conversa"
              class="new-btn flex items-center gap-[var(--spacing-1)] bg-transparent border border-[var(--border-muted)] rounded-[var(--shape-button)] text-[var(--text-muted)] text-body-xs font-mono tracking-wider cursor-pointer px-[var(--spacing-2)] py-[var(--spacing-1)] transition-colors hover:border-[var(--primary)] hover:text-[var(--primary-contrast)]"
              @click="handleNewConversation"
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M12 20h9" />
                <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z" />
              </svg>
              NOVA
            </button>
            <button
              :title="theme.mode.value === 'dark' ? 'Modo claro' : 'Modo escuro'"
              class="w-8 h-8 flex items-center justify-center bg-transparent border-0 rounded-[var(--shape-button)] text-[var(--text-muted)] cursor-pointer transition-colors hover:bg-[var(--bg-hover)] hover:text-[var(--text-default)]"
              @click="theme.toggle()"
            >
              <svg v-if="theme.mode.value === 'dark'" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="4" />
                <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41" />
              </svg>
              <svg v-else width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
              </svg>
            </button>
            <button
              title="Configurações"
              class="w-8 h-8 flex items-center justify-center bg-transparent border-0 rounded-[var(--shape-button)] text-[var(--text-muted)] cursor-pointer transition-colors hover:bg-[var(--bg-hover)] hover:text-[var(--text-default)]"
              @click="settingsOpen = true"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="3" />
                <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z" />
              </svg>
            </button>
          </div>
        </header>

        <!-- Error banner -->
        <div
          v-if="error"
          class="px-[var(--spacing-6)] py-[var(--spacing-2)] bg-[var(--danger-mask,var(--bg-hover))] border-b border-[var(--danger-border)] flex items-center gap-[var(--spacing-2)] flex-shrink-0"
        >
          <span class="text-[var(--danger)] text-body-xxs">✕</span>
          <span class="font-mono text-body-xxs text-[var(--danger-contrast)] tracking-wide flex-1">
            {{ error.message }}
          </span>
          <button
            v-if="lastIsAssistant && !isLoading"
            class="bg-transparent border border-[var(--danger-border)] rounded-[var(--shape-button)] text-[var(--danger)] text-body-xxs font-mono tracking-wider cursor-pointer px-[var(--spacing-2)] py-[var(--spacing-1)]"
            @click="reload()"
          >
            RETRY
          </button>
        </div>

        <MessageList :messages="displayMessages" :is-loading="isLoading" />

        <!-- Regenerate toolbar -->
        <div
          v-if="!isLoading && !error && lastIsAssistant"
          class="py-[var(--spacing-1)] flex justify-center flex-shrink-0"
        >
          <button
            class="flex items-center gap-[var(--spacing-1)] bg-transparent border border-[var(--border-muted)] rounded-[var(--shape-button)] text-[var(--text-muted)] text-body-xxs font-mono tracking-wider cursor-pointer px-[var(--spacing-3)] py-[var(--spacing-1)] transition-colors hover:border-[var(--primary)] hover:text-[var(--primary-contrast)]"
            @click="reload()"
          >
            <svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor">
              <path fill-rule="evenodd" d="M8 3a5 5 0 104.546 2.914.5.5 0 00-.908-.417A4 4 0 118 4V3z" clip-rule="evenodd" />
              <path d="M8 4.466V.534a.25.25 0 00-.41-.192L5.23 2.308a.25.25 0 000 .384l2.36 1.966A.25.25 0 008 4.466z" />
            </svg>
            REGENERAR
          </button>
        </div>

        <ChatInput
          :is-loading="isLoading"
          :disabled="noKey"
          :disabled-reason="noKey ? 'Configure sua chave de API em Settings para começar' : undefined"
          @send="handleSend"
          @stop="stop"
        />
      </div>
    </div>
  </div>

  <SettingsDrawer :open="settingsOpen" :settings="settings" @close="settingsOpen = false" />
</template>

<style>
@keyframes fadeInChat {
  from { opacity: 0; transform: translateY(6px); }
  to   { opacity: 1; transform: translateY(0); }
}
@keyframes fadeInEmpty {
  from { opacity: 0; }
  to   { opacity: 1; }
}
</style>
