// templates/react/tanstack-chat-ai/src/components/ChatInput.tsx
import { useRef, useState, type KeyboardEvent, type ChangeEvent } from 'react'
import { useAudioRecorder } from '../hooks/useAudioRecorder'

interface AttachedFile {
  name: string
  content: string
}

interface Props {
  onSend: (text: string) => void
  onStop: () => void
  isLoading: boolean
  disabled: boolean
  disabledReason?: string
}

// 32KB limit — stays safely within Azion edge function body limits
const MAX_SIZE = 32 * 1024
const ACCEPTED = '.txt,.md,.ts,.tsx,.js,.jsx,.py,.json,.yaml,.yml,.html,.css,.sql,.sh,.csv,.xml,.toml,.go,.rs,.java,.kt,.swift,.rb,.php,.c,.cpp,.h'

export function ChatInput({ onSend, onStop, isLoading, disabled, disabledReason }: Props) {
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [attachedFiles, setAttachedFiles] = useState<AttachedFile[]>([])

  function handleTranscript(text: string) {
    const el = textareaRef.current
    if (!el) return
    el.value = el.value ? `${el.value} ${text}` : text
    el.style.height = 'auto'
    el.style.height = Math.min(el.scrollHeight, 160) + 'px'
    el.focus()
  }

  const { isRecording, supported: micSupported, start: startRec, stop: stopRec } = useAudioRecorder(handleTranscript)

  function handleKeyDown(e: KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      submit()
    }
  }

  function submit() {
    const userText = textareaRef.current?.value.trim() ?? ''
    if ((!userText && attachedFiles.length === 0) || isLoading || disabled) return

    const fileBlocks = attachedFiles
      .map((f) => `[Arquivo: ${f.name}]\n\`\`\`\n${f.content}\n\`\`\``)
      .join('\n\n')

    const fullText = fileBlocks
      ? userText ? `${fileBlocks}\n\n${userText}` : fileBlocks
      : userText

    onSend(fullText)

    if (textareaRef.current) {
      textareaRef.current.value = ''
      textareaRef.current.style.height = 'auto'
    }
    setAttachedFiles([])
  }

  async function handleFileChange(e: ChangeEvent<HTMLInputElement>) {
    const files = Array.from(e.target.files ?? [])
    const added: AttachedFile[] = []
    const skipped: string[] = []

    for (const file of files) {
      if (file.size > MAX_SIZE) {
        skipped.push(file.name)
        continue
      }
      try {
        const content = await file.text()
        added.push({ name: file.name, content })
      } catch {
        // skip unreadable files
      }
    }

    if (skipped.length > 0) {
      alert(`Arquivos ignorados (limite 32KB): ${skipped.join(', ')}`)
    }

    setAttachedFiles((prev) => {
      const existing = new Set(prev.map((f) => f.name))
      return [...prev, ...added.filter((f) => !existing.has(f.name))]
    })

    if (e.target) e.target.value = ''
  }

  function toggleMic() {
    if (isRecording) stopRec()
    else startRec()
  }

  const canSend = !disabled && !isLoading

  return (
    <div
      style={{
        background: '#111111',
        padding: '12px 20px 20px',
        flexShrink: 0,
      }}
    >
      {disabledReason && (
        <p
          style={{
            fontSize: '11px',
            fontFamily: 'monospace',
            color: '#666666',
            marginBottom: '10px',
            textAlign: 'center',
            letterSpacing: '0.04em',
          }}
        >
          {disabledReason}
        </p>
      )}

      {/* Rounded input container */}
      <div
        style={{
          maxWidth: '720px',
          margin: '0 auto',
          background: '#1C1C1C',
          border: '1px solid rgba(255,255,255,0.1)',
          borderRadius: '16px',
          overflow: 'hidden',
          transition: 'border-color 0.15s ease',
        }}
        onFocusCapture={(e) => {
          e.currentTarget.style.borderColor = 'rgba(254,96,31,0.35)'
        }}
        onBlurCapture={(e) => {
          e.currentTarget.style.borderColor = 'rgba(255,255,255,0.1)'
        }}
      >
        {/* File chips inside the container */}
        {attachedFiles.length > 0 && (
          <div
            style={{
              padding: '10px 12px 0',
              display: 'flex',
              flexWrap: 'wrap',
              gap: '6px',
            }}
          >
            {attachedFiles.map((f) => (
              <div
                key={f.name}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '5px',
                  padding: '3px 8px 3px 8px',
                  background: 'rgba(254,96,31,0.1)',
                  border: '0.8px solid rgba(254,96,31,0.28)',
                  borderRadius: '6px',
                  fontSize: '11px',
                  fontFamily: 'monospace',
                  color: '#FF8E4D',
                  letterSpacing: '0.02em',
                }}
              >
                <FileIcon />
                <span style={{ maxWidth: '160px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  {f.name}
                </span>
                <button
                  onClick={() => setAttachedFiles((p) => p.filter((x) => x.name !== f.name))}
                  style={{
                    background: 'transparent',
                    border: 'none',
                    color: '#FF8E4D',
                    cursor: 'pointer',
                    padding: '0 0 0 2px',
                    lineHeight: 1,
                    opacity: 0.6,
                    fontSize: '12px',
                    transition: 'opacity 0.15s',
                  }}
                  onMouseEnter={(e) => { e.currentTarget.style.opacity = '1' }}
                  onMouseLeave={(e) => { e.currentTarget.style.opacity = '0.6' }}
                >
                  ×
                </button>
              </div>
            ))}
          </div>
        )}

        {/* Input row */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            padding: '4px 8px 4px 4px',
            gap: '4px',
          }}
        >
          {/* + / Attach button */}
          <button
            onClick={() => fileInputRef.current?.click()}
            disabled={!canSend}
            title="Anexar arquivo"
            style={{
              width: '36px',
              height: '36px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              flexShrink: 0,
              background: 'transparent',
              border: 'none',
              borderRadius: '10px',
              color: canSend ? '#4D4D4D' : '#2D2D2D',
              cursor: canSend ? 'pointer' : 'not-allowed',
              transition: 'all 0.15s ease',
              fontSize: '22px',
              fontWeight: 300,
              lineHeight: 1,
            }}
            onMouseEnter={(e) => {
              if (canSend) {
                e.currentTarget.style.background = 'rgba(255,255,255,0.06)'
                e.currentTarget.style.color = '#FCFCFC'
              }
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = 'transparent'
              e.currentTarget.style.color = canSend ? '#4D4D4D' : '#2D2D2D'
            }}
          >
            +
          </button>

          <input
            ref={fileInputRef}
            type="file"
            accept={ACCEPTED}
            multiple
            style={{ display: 'none' }}
            onChange={handleFileChange}
          />

          {/* Textarea */}
          <textarea
            ref={textareaRef}
            rows={1}
            disabled={disabled || isLoading}
            onKeyDown={handleKeyDown}
            placeholder={
              disabled
                ? 'Configure a chave de API em Settings…'
                : isLoading
                ? 'Gerando…'
                : 'Pergunte alguma coisa'
            }
            style={{
              flex: 1,
              background: 'transparent',
              border: 'none',
              padding: '10px 4px',
              fontSize: '15px',
              color: disabled ? '#4D4D4D' : '#FCFCFC',
              fontFamily: "'Sora', sans-serif",
              resize: 'none',
              outline: 'none',
              minHeight: '40px',
              maxHeight: '160px',
              overflowY: 'auto',
              lineHeight: '1.5',
            }}
            onInput={(e) => {
              const el = e.currentTarget
              el.style.height = 'auto'
              el.style.height = Math.min(el.scrollHeight, 160) + 'px'
            }}
          />

          {/* Mic button */}
          {micSupported && (
            <button
              onClick={toggleMic}
              disabled={disabled}
              title={isRecording ? 'Parar gravação' : 'Entrada de voz'}
              style={{
                width: '36px',
                height: '36px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0,
                background: isRecording ? 'rgba(255,77,77,0.15)' : 'transparent',
                border: isRecording ? '0.8px solid rgba(255,77,77,0.4)' : 'none',
                borderRadius: '10px',
                color: isRecording ? '#FF4D4D' : (disabled ? '#2D2D2D' : '#4D4D4D'),
                cursor: disabled ? 'not-allowed' : 'pointer',
                transition: 'all 0.15s ease',
                animation: isRecording ? 'mic-pulse 1.2s ease-in-out infinite' : 'none',
              }}
              onMouseEnter={(e) => {
                if (!disabled && !isRecording) {
                  e.currentTarget.style.background = 'rgba(255,255,255,0.06)'
                  e.currentTarget.style.color = '#FCFCFC'
                }
              }}
              onMouseLeave={(e) => {
                if (!isRecording) {
                  e.currentTarget.style.background = 'transparent'
                  e.currentTarget.style.color = disabled ? '#2D2D2D' : '#4D4D4D'
                }
              }}
            >
              <MicIcon />
            </button>
          )}

          {/* Send / Stop button */}
          {isLoading ? (
            <button
              onClick={onStop}
              title="Parar geração"
              style={{
                width: '36px',
                height: '36px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0,
                background: '#FCFCFC',
                border: 'none',
                borderRadius: '10px',
                cursor: 'pointer',
                color: '#0D0D0D',
                transition: 'background 0.15s ease',
              }}
              onMouseEnter={(e) => { e.currentTarget.style.background = '#E0E0E0' }}
              onMouseLeave={(e) => { e.currentTarget.style.background = '#FCFCFC' }}
            >
              <svg width="12" height="12" viewBox="0 0 12 12" fill="currentColor">
                <rect x="1" y="1" width="10" height="10" rx="2" />
              </svg>
            </button>
          ) : (
            <button
              onClick={submit}
              disabled={disabled}
              title="Enviar"
              style={{
                width: '36px',
                height: '36px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0,
                background: disabled ? 'rgba(255,255,255,0.08)' : '#FCFCFC',
                border: 'none',
                borderRadius: '10px',
                cursor: disabled ? 'not-allowed' : 'pointer',
                color: disabled ? '#4D4D4D' : '#0D0D0D',
                transition: 'background 0.15s ease',
              }}
              onMouseEnter={(e) => {
                if (!disabled) e.currentTarget.style.background = '#E0E0E0'
              }}
              onMouseLeave={(e) => {
                if (!disabled) e.currentTarget.style.background = '#FCFCFC'
              }}
            >
              <SendIcon />
            </button>
          )}
        </div>
      </div>

      <style>{`
        @keyframes mic-pulse {
          0%, 100% { box-shadow: 0 0 0 0 rgba(255,77,77,0); }
          50% { box-shadow: 0 0 0 4px rgba(255,77,77,0.15); }
        }
      `}</style>

      <p
        style={{
          textAlign: 'center',
          fontSize: '11px',
          color: '#2A2A2A',
          marginTop: '10px',
          fontFamily: 'monospace',
          letterSpacing: '0.03em',
        }}
      >
        Powered by Azion · Keys are never stored server-side
      </p>
    </div>
  )
}

function SendIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
      <path
        d="M8 1L8 15M8 1L3 6M8 1L13 6"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

function MicIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
    </svg>
  )
}

function FileIcon() {
  return (
    <svg
      width="10"
      height="10"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}

// templates/vue/vue-chat-ai/components/ChatInput.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useAudioRecorder } from '~/composables/useAudioRecorder'

interface AttachedFile { name: string; content: string }

const props = defineProps<{
  isLoading: boolean
  disabled: boolean
  disabledReason?: string
}>()

const emit = defineEmits<{
  send: [text: string]
  stop: []
}>()

const MAX_SIZE = 32 * 1024
const ACCEPTED = '.txt,.md,.ts,.tsx,.js,.jsx,.py,.json,.yaml,.yml,.html,.css,.sql,.sh,.csv,.xml,.toml,.go,.rs,.java,.kt,.swift,.rb,.php,.c,.cpp,.h'

const textareaRef = ref<HTMLTextAreaElement | null>(null)
const fileInputRef = ref<HTMLInputElement | null>(null)
const attachedFiles = ref<AttachedFile[]>([])

function handleTranscript(text: string) {
  const el = textareaRef.value
  if (!el) return
  el.value = el.value ? `${el.value} ${text}` : text
  el.style.height = 'auto'
  el.style.height = Math.min(el.scrollHeight, 160) + 'px'
  el.focus()
}

const { isRecording, supported: micSupported, start: startRec, stop: stopRec } = useAudioRecorder(handleTranscript)

function handleKeyDown(e: KeyboardEvent) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    submit()
  }
}

function submit() {
  const userText = textareaRef.value?.value.trim() ?? ''
  if ((!userText && attachedFiles.value.length === 0) || props.isLoading || props.disabled) return

  const fileBlocks = attachedFiles.value
    .map((f) => `[Arquivo: ${f.name}]\n\`\`\`\n${f.content}\n\`\`\``)
    .join('\n\n')

  const fullText = fileBlocks
    ? userText ? `${fileBlocks}\n\n${userText}` : fileBlocks
    : userText

  emit('send', fullText)

  if (textareaRef.value) {
    textareaRef.value.value = ''
    textareaRef.value.style.height = 'auto'
  }
  attachedFiles.value = []
}

async function handleFileChange(e: Event) {
  const target = e.target as HTMLInputElement
  const files = Array.from(target.files ?? [])
  const added: AttachedFile[] = []
  const skipped: string[] = []

  for (const file of files) {
    if (file.size > MAX_SIZE) {
      skipped.push(file.name)
      continue
    }
    try {
      const content = await file.text()
      added.push({ name: file.name, content })
    } catch {
      // skip unreadable files
    }
  }

  if (skipped.length > 0) {
    alert(`Arquivos ignorados (limite 32KB): ${skipped.join(', ')}`)
  }

  const existing = new Set(attachedFiles.value.map((f) => f.name))
  attachedFiles.value = [...attachedFiles.value, ...added.filter((f) => !existing.has(f.name))]

  if (target) target.value = ''
}

function removeFile(name: string) {
  attachedFiles.value = attachedFiles.value.filter((x) => x.name !== name)
}

function toggleMic() {
  if (isRecording.value) stopRec()
  else startRec()
}

function onTextareaInput(e: Event) {
  const el = e.currentTarget as HTMLTextAreaElement
  el.style.height = 'auto'
  el.style.height = Math.min(el.scrollHeight, 160) + 'px'
}

const canSend = computed(() => !props.disabled && !props.isLoading)
</script>

<template>
  <div class="bg-[var(--bg-canvas)] px-[var(--spacing-5)] pt-[var(--spacing-3)] pb-[var(--spacing-3)] flex-shrink-0">
    <p
      v-if="disabledReason"
      class="text-body-xxs font-mono text-[var(--text-muted)] mb-[var(--spacing-2)] text-center tracking-wide"
    >
      {{ disabledReason }}
    </p>

    <!-- Rounded input container: two rows -->
    <div
      class="chat-input-shell max-w-[720px] mx-auto bg-[var(--bg-surface)] border border-[var(--border-muted)] rounded-[var(--shape-card)] transition-colors p-[var(--spacing-3)] flex flex-col gap-[var(--spacing-2)]"
    >
      <!-- File chips -->
      <div
        v-if="attachedFiles.length > 0"
        class="flex flex-wrap gap-[var(--spacing-1)]"
      >
        <div
          v-for="f in attachedFiles"
          :key="f.name"
          class="flex items-center gap-[var(--spacing-1)] px-[var(--spacing-2)] py-[var(--spacing-1)] bg-[var(--primary-mask)] border border-[var(--primary)] rounded-[var(--shape-button)] text-body-xxs font-mono text-[var(--primary-contrast)] tracking-wide"
        >
          <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
            <polyline points="14 2 14 8 20 8" />
          </svg>
          <span class="max-w-[160px] overflow-hidden text-ellipsis whitespace-nowrap">
            {{ f.name }}
          </span>
          <button
            class="chip-remove bg-transparent border-0 text-[var(--primary-contrast)] cursor-pointer p-0 pl-[var(--spacing-1)] leading-none text-body-xs opacity-60 transition-opacity hover:opacity-100"
            @click="removeFile(f.name)"
          >
            ×
          </button>
        </div>
      </div>

      <!-- Row 1: Textarea (full width) -->
      <textarea
        ref="textareaRef"
        :rows="1"
        :disabled="disabled || isLoading"
        :placeholder="
          disabled
            ? 'Configure a chave de API em Settings para começar.'
            : isLoading
            ? 'Gerando resposta…'
            : 'Pergunte sobre a documentação da Azion…'
        "
        class="w-full bg-transparent border-0 text-body-md resize-none outline-none min-h-[40px] max-h-[160px] overflow-y-auto"
        :class="disabled ? 'text-[var(--text-muted)]' : 'text-[var(--text-default)]'"
        style="line-height: 1.5;"
        @keydown="handleKeyDown"
        @input="onTextareaInput"
      />

      <input
        ref="fileInputRef"
        type="file"
        :accept="ACCEPTED"
        multiple
        class="hidden"
        @change="handleFileChange"
      />

      <!-- Row 2: Left tools + right actions -->
      <div class="flex items-center justify-between gap-[var(--spacing-2)]">
        <div class="flex items-center gap-[var(--spacing-1)]">
          <button
            title="Anexar arquivo"
            :disabled="!canSend"
            class="w-8 h-8 flex items-center justify-center flex-shrink-0 bg-transparent border-0 rounded-[var(--shape-elements)] transition-colors text-heading-md font-light leading-none"
            :class="canSend
              ? 'text-[var(--text-muted)] cursor-pointer hover:bg-[var(--bg-hover)] hover:text-[var(--text-default)]'
              : 'text-[var(--text-disabled)] cursor-not-allowed'"
            @click="fileInputRef?.click()"
          >
            +
          </button>
        </div>

        <div class="flex items-center gap-[var(--spacing-1)]">
          <!-- Mic button -->
          <button
            v-if="micSupported"
            :disabled="disabled"
            :title="isRecording ? 'Parar gravação' : 'Entrada de voz'"
            class="w-8 h-8 flex items-center justify-center flex-shrink-0 rounded-[var(--shape-elements)] transition-colors"
            :class="[
              isRecording
                ? 'bg-[var(--danger-mask,var(--bg-hover))] border border-[var(--danger-border)] text-[var(--danger)]'
                : disabled
                  ? 'bg-transparent border-0 text-[var(--text-disabled)] cursor-not-allowed'
                  : 'bg-transparent border-0 text-[var(--text-muted)] cursor-pointer hover:bg-[var(--bg-hover)] hover:text-[var(--text-default)]',
            ]"
            :style="isRecording ? { animation: 'mic-pulse 1.2s ease-in-out infinite' } : undefined"
            @click="toggleMic"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3z" />
              <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
              <line x1="12" x2="12" y1="19" y2="22" />
            </svg>
          </button>

          <!-- Send / Stop -->
          <button
            v-if="isLoading"
            title="Parar geração"
            class="w-8 h-8 flex items-center justify-center flex-shrink-0 bg-[var(--bg-contrast)] border-0 rounded-[var(--shape-elements)] cursor-pointer text-[var(--text-contrast)] transition-colors hover:bg-[var(--bg-hover)]"
            @click="emit('stop')"
          >
            <svg width="12" height="12" viewBox="0 0 12 12" fill="currentColor">
              <rect x="1" y="1" width="10" height="10" rx="2" />
            </svg>
          </button>
          <button
            v-else
            title="Enviar"
            :disabled="disabled"
            class="w-8 h-8 flex items-center justify-center flex-shrink-0 border-0 rounded-[var(--shape-elements)] transition-colors"
            :class="disabled
              ? 'bg-[var(--bg-disabled)] text-[var(--text-muted)] cursor-not-allowed'
              : 'bg-[var(--bg-contrast)] text-[var(--text-contrast)] cursor-pointer hover:opacity-90'"
            @click="submit"
          >
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
              <path
                d="M8 1L8 15M8 1L3 6M8 1L13 6"
                stroke="currentColor"
                stroke-width="1.8"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </button>
        </div>
      </div>
    </div>

    <p class="text-center text-body-xxs text-[var(--text-disabled)] mt-[var(--spacing-2)] font-mono tracking-wide">
      Powered by Azion · Keys are never stored server-side
    </p>
  </div>
</template>

<style>
@keyframes mic-pulse {
  0%, 100% { box-shadow: 0 0 0 0 transparent; }
  50% { box-shadow: 0 0 0 4px var(--danger-mask, transparent); }
}
.chat-input-shell:focus-within {
  border-color: var(--primary);
}
</style>
