// templates/angular/angular-starter-buttercms/src/app/layout/components/header/header.component.ts
import {Component, HostListener, Input, OnInit, ViewChild} from '@angular/core';
import {NavigationEnd, Router} from '@angular/router';
import {filter} from 'rxjs/operators';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html'
})
export class HeaderComponent implements OnInit {
  public isSticky = false;
  public toggler = false;

  public activeUrl;

  @Input() menuData;
  @ViewChild('navbarArea') navbarArea;

  constructor(private router: Router) {
    this.onScroll();
  }

  ngOnInit(): void {
    this.activeUrl = this.router.url;
    this.router.events
      .pipe(filter(event => event instanceof NavigationEnd))
      .subscribe((event: NavigationEnd) => {
        this.activeUrl = event.url;
      });
  }

  get menuItems() {
    if (this.menuData) {
      return this.menuData.data.data.navigation_menu[0].menu_items;
    }
    return [];
  }

  isActive(url) {
    if (url) {
      return url[0] === this.activeUrl;
    }
    return false;
  }

  @HostListener('window:scroll', ['$event'])
  onScroll() {
    if (this.navbarArea) {
      const sticky = this.navbarArea.nativeElement.offsetTop;
      this.isSticky = window.pageYOffset > sticky;
    } else {
      this.isSticky = false;
    }

    const sections = document.querySelectorAll('.page-scroll');
    const scrollPos = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop;

    const de = document.documentElement;

    for (let i = 0; i < sections.length; i++) {
      const currLink = sections[i];
      const currLinkHref = currLink.getAttribute('href');
      const val = currLinkHref.replace('/', '');
      const refElement = document.querySelector(val);
      if (refElement) {
        const box = refElement.getBoundingClientRect();
        const top = box.top + window.pageYOffset - de.clientTop;

        const scrollTopMinus = scrollPos + 73;

        const h = refElement.getBoundingClientRect().height;

        if (refElement && top <= scrollTopMinus && (top + h > scrollTopMinus)) {
          this.activeUrl = '/' + currLinkHref;
        }
      }
    }
  }

  onTogglerClick() {
    this.toggler = !this.toggler;
  }

  onMenuItemClick() {
    this.toggler = false;
  }

  get isTogglerActive() {
    return this.toggler;
  }

}

<header class="header">
  <div #navbarArea id="" class="navbar-area" [class.sticky]="isSticky">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-12">
          <nav class="navbar navbar-expand-lg">
            <a class="navbar-brand" href="https://buttercms.com">
              <img src="https://cdn.buttercms.com/PBral0NQGmmFzV0uG7Q6" alt="Logo" />
            </a>
            <button [ngClass]="{'navbar-toggler': true, 'active': isTogglerActive}" (click)="onTogglerClick()" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse sub-menu-bar" [class.show]="isTogglerActive" id="navbarSupportedContent">
              <div class="ms-auto">
                <ul id="nav" class="navbar-nav ms-auto">
                  <ng-container *ngFor="let item of menuItems">
                    <li class="nav-item">
                      <a class="page-scroll" [class.active]="isActive(['/' + item.url])" [routerLinkActive]="['active']" (click)="onMenuItemClick()" href="{{item.url}}">{{item.label}}</a>
                    </li>
                  </ng-container>
                </ul>
              </div>
            </div> <!-- navbar collapse -->

          </nav> <!-- navbar -->
        </div>
      </div> <!-- row -->
    </div> <!-- container -->
  </div> <!-- navbar area -->
</header>

// templates/nuxt/nuxt-starter-buttercms/components/Header.vue
<script setup>
import { onMounted, ref } from "vue";
const props = defineProps(["menuItems", "activeLink"]);

const isSticky = ref(true);
const isTogglerActive = ref(false);

const togglToggler = () => {
  isTogglerActive.value = !isTogglerActive.value;
};

const headerNavbar = ref(null);
const onScroll = () => {
  if (headerNavbar.value) {
    const sticky = headerNavbar.value.offsetTop;
    isSticky.value = window.scrollY > sticky;
  }
};
onMounted(() => {
  onScroll();
  window.document.addEventListener("scroll", onScroll, { passive: true });
  return () => window.document.removeEventListener("scroll", onScroll);
});
</script>

<template>
  <header class="header">
    <div class="navbar-area" ref="headerNavbar" :class="{ sticky: isSticky }">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-12">
            <nav class="navbar navbar-expand-lg">
              <a class="navbar-brand" href="https://buttercms.com">
                <img
                  src="https://cdn.buttercms.com/PBral0NQGmmFzV0uG7Q6"
                  alt="Logo"
                />
              </a>
              <button
                class="navbar-toggler"
                :class="{ active: isTogglerActive }"
                @click="togglToggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span class="toggler-icon"></span>
                <span class="toggler-icon"></span>
                <span class="toggler-icon"></span>
              </button>

              <div
                :class="{ show: isTogglerActive }"
                class="collapse navbar-collapse sub-menu-bar"
                id="navbarSupportedContent"
              >
                <div class="ms-auto">
                  <ul id="nav" class="navbar-nav ms-auto">
                    <li
                      v-for="menuItem in props.menuItems"
                      :key="menuItem.url"
                      class="nav-item"
                    >
                      <a
                        class="nav-link page-scroll"
                        :class="{ active: activeLink === '/' + menuItem.url }"
                        :href="'/' + menuItem.url"
                        @click="isTogglerActive = false"
                        >{{ menuItem.label }}</a
                      >
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </header>
</template>

<style scoped></style>
