// templates/vue/vue-chat-ai/components/HistoryDrawer.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { SavedConversation } from '~/composables/useConversationHistory'

const props = defineProps<{
  open: boolean
  conversations: SavedConversation[]
  currentId: string
}>()

const emit = defineEmits<{
  close: []
  load: [conv: SavedConversation]
  delete: [id: string]
  new: []
}>()

function relativeTime(ts: number): string {
  const diff = Date.now() - ts
  const m = Math.floor(diff / 60000)
  const h = Math.floor(diff / 3600000)
  const d = Math.floor(diff / 86400000)
  if (m < 1) return 'agora'
  if (m < 60) return `${m}min atrás`
  if (h < 24) return `${h}h atrás`
  return `${d}d atrás`
}

const sortedConvs = computed(() =>
  [...props.conversations].sort((a, b) => b.timestamp - a.timestamp),
)

function msgCount(conv: SavedConversation) {
  return conv.messages.filter((m) => m.role === 'user' || m.role === 'assistant').length
}
</script>

<template>
  <div v-if="open" class="fixed inset-0 z-50 flex">
    <div
      class="absolute inset-0 bg-[var(--bg-backdrop)]"
      @click="emit('close')"
    />

    <div
      class="relative h-full w-full max-w-[320px] bg-[var(--bg-surface)] border-r border-[var(--border-muted)] flex flex-col shadow-[var(--shadow-md)]"
    >
      <!-- Header -->
      <div
        class="flex items-center justify-between px-[var(--spacing-5)] h-14 border-b border-[var(--border-muted)] flex-shrink-0"
      >
        <span class="font-mono text-body-xxs text-[var(--text-default)] tracking-widest uppercase">
          Histórico
        </span>
        <div class="flex gap-[var(--spacing-2)] items-center">
          <button
            class="flex items-center gap-[var(--spacing-1)] bg-transparent border border-[var(--primary)] rounded-[var(--shape-flat)] text-[var(--primary-contrast)] text-body-xxs font-mono tracking-wider cursor-pointer px-[var(--spacing-3)] py-[var(--spacing-1)] transition-colors hover:bg-[var(--primary-mask)]"
            @click="emit('new')"
          >
            + NOVA
          </button>
          <button
            class="bg-transparent border-0 text-[var(--text-muted)] cursor-pointer text-body-md leading-none p-[var(--spacing-1)] transition-colors hover:text-[var(--text-default)]"
            @click="emit('close')"
          >
            ✕
          </button>
        </div>
      </div>

      <!-- List -->
      <div class="flex-1 overflow-y-auto py-[var(--spacing-2)]">
        <p
          v-if="conversations.length === 0"
          class="text-center px-[var(--spacing-5)] py-[var(--spacing-10)] font-mono text-body-xxs text-[var(--text-disabled)] tracking-wide uppercase"
        >
          Nenhuma conversa salva
        </p>
        <div
          v-for="conv in sortedConvs"
          :key="conv.id"
          class="hist-item flex items-center pr-[var(--spacing-3)] pl-[var(--spacing-4)] transition-colors"
          :class="conv.id === currentId ? 'bg-[var(--primary-mask)] hist-item--current' : 'bg-transparent hover:bg-[var(--bg-hover)]'"
          :style="{ borderLeft: `2px solid ${conv.id === currentId ? 'var(--primary)' : 'transparent'}` }"
        >
          <button
            class="flex-1 bg-transparent border-0 py-[var(--spacing-3)] text-left cursor-pointer overflow-hidden min-w-0"
            @click="emit('load', conv)"
          >
            <div
              class="text-body-sm overflow-hidden text-ellipsis whitespace-nowrap mb-[var(--spacing-1)]"
              :class="conv.id === currentId ? 'text-[var(--text-default)]' : 'text-[var(--text-default)] opacity-80'"
            >
              {{ conv.title }}
            </div>
            <div class="text-body-xxs font-mono text-[var(--text-muted)] tracking-wide">
              {{ relativeTime(conv.timestamp) }} · {{ msgCount(conv) }} msgs
            </div>
          </button>
          <button
            title="Excluir conversa"
            class="bg-transparent border-0 text-[var(--text-disabled)] cursor-pointer p-[var(--spacing-1)] flex-shrink-0 transition-colors leading-none text-body-xs hover:text-[var(--danger)]"
            @click.stop="emit('delete', conv.id)"
          >
            ✕
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// templates/react/tanstack-chat-ai/src/components/HistoryDrawer.tsx
import type { SavedConversation } from '../hooks/useConversationHistory'

interface Props {
  open: boolean
  onClose: () => void
  conversations: SavedConversation[]
  currentId: string
  onLoad: (conv: SavedConversation) => void
  onDelete: (id: string) => void
  onNew: () => void
}

function relativeTime(ts: number): string {
  const diff = Date.now() - ts
  const m = Math.floor(diff / 60000)
  const h = Math.floor(diff / 3600000)
  const d = Math.floor(diff / 86400000)
  if (m < 1) return 'agora'
  if (m < 60) return `${m}min atrás`
  if (h < 24) return `${h}h atrás`
  return `${d}d atrás`
}

export function HistoryDrawer({ open, onClose, conversations, currentId, onLoad, onDelete, onNew }: Props) {
  if (!open) return null

  return (
    <div style={{ position: 'fixed', inset: 0, zIndex: 50, display: 'flex' }}>
      <div
        style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.7)' }}
        onClick={onClose}
      />

      <div
        style={{
          position: 'relative',
          height: '100%',
          width: '100%',
          maxWidth: '320px',
          background: '#0A0A0A',
          borderRight: '0.8px solid rgba(255,255,255,0.08)',
          display: 'flex',
          flexDirection: 'column',
          boxShadow: '24px 0 48px rgba(0,0,0,0.6)',
        }}
      >
        {/* Header */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '0 20px',
            height: '56px',
            borderBottom: '0.8px solid rgba(255,255,255,0.08)',
            flexShrink: 0,
          }}
        >
          <span
            style={{
              fontFamily: 'monospace',
              fontSize: '11px',
              color: '#B2B2B2',
              letterSpacing: '0.08em',
              textTransform: 'uppercase',
            }}
          >
            Histórico
          </span>
          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
            <button
              onClick={onNew}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '5px',
                background: 'transparent',
                border: '0.8px solid rgba(254,96,31,0.3)',
                borderRadius: '4px',
                color: '#FF8E4D',
                fontSize: '10px',
                fontFamily: 'monospace',
                letterSpacing: '0.06em',
                cursor: 'pointer',
                padding: '4px 10px',
                transition: 'all 0.15s ease',
              }}
              onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'rgba(254,96,31,0.6)' }}
              onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'rgba(254,96,31,0.3)' }}
            >
              + NOVA
            </button>
            <button
              onClick={onClose}
              style={{
                background: 'transparent',
                border: 'none',
                color: '#4D4D4D',
                cursor: 'pointer',
                fontSize: '16px',
                lineHeight: 1,
                padding: '4px',
                transition: 'color 0.15s ease',
              }}
              onMouseEnter={(e) => { e.currentTarget.style.color = '#FCFCFC' }}
              onMouseLeave={(e) => { e.currentTarget.style.color = '#4D4D4D' }}
            >
              ✕
            </button>
          </div>
        </div>

        {/* List */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '8px 0' }}>
          {conversations.length === 0 && (
            <p
              style={{
                textAlign: 'center',
                padding: '40px 20px',
                fontFamily: 'monospace',
                fontSize: '11px',
                color: '#333333',
                letterSpacing: '0.04em',
                textTransform: 'uppercase',
              }}
            >
              Nenhuma conversa salva
            </p>
          )}
          {conversations
            .slice()
            .sort((a, b) => b.timestamp - a.timestamp)
            .map((conv) => {
              const isActive = conv.id === currentId
              const msgCount = conv.messages.filter(
                (m) => m.role === 'user' || m.role === 'assistant',
              ).length
              return (
                <div
                  key={conv.id}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    padding: '0 12px 0 18px',
                    borderLeft: isActive ? '2px solid #FE601F' : '2px solid transparent',
                    background: isActive ? 'rgba(254,96,31,0.06)' : 'transparent',
                    transition: 'background 0.15s ease',
                  }}
                  onMouseEnter={(e) => {
                    if (!isActive) e.currentTarget.style.background = 'rgba(255,255,255,0.03)'
                  }}
                  onMouseLeave={(e) => {
                    if (!isActive) e.currentTarget.style.background = 'transparent'
                  }}
                >
                  <button
                    onClick={() => onLoad(conv)}
                    style={{
                      flex: 1,
                      background: 'transparent',
                      border: 'none',
                      padding: '12px 0',
                      textAlign: 'left',
                      cursor: 'pointer',
                      overflow: 'hidden',
                      minWidth: 0,
                    }}
                  >
                    <div
                      style={{
                        fontSize: '13px',
                        fontFamily: "'Sora', sans-serif",
                        color: isActive ? '#FCFCFC' : '#B2B2B2',
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                        whiteSpace: 'nowrap',
                        marginBottom: '4px',
                      }}
                    >
                      {conv.title}
                    </div>
                    <div
                      style={{
                        fontSize: '10px',
                        fontFamily: 'monospace',
                        color: '#4D4D4D',
                        letterSpacing: '0.04em',
                      }}
                    >
                      {relativeTime(conv.timestamp)} · {msgCount} msgs
                    </div>
                  </button>
                  <button
                    onClick={(e) => {
                      e.stopPropagation()
                      onDelete(conv.id)
                    }}
                    style={{
                      background: 'transparent',
                      border: 'none',
                      color: '#2D2D2D',
                      cursor: 'pointer',
                      padding: '6px',
                      flexShrink: 0,
                      transition: 'color 0.15s ease',
                      lineHeight: 1,
                      fontSize: '12px',
                    }}
                    onMouseEnter={(e) => { e.currentTarget.style.color = '#FF4D4D' }}
                    onMouseLeave={(e) => { e.currentTarget.style.color = '#2D2D2D' }}
                    title="Excluir conversa"
                  >
                    ✕
                  </button>
                </div>
              )
            })}
        </div>
      </div>
    </div>
  )
}
