// templates/vue/vue-chat-ai/components/MessageList.vue
<script setup lang="ts">
import { nextTick, ref, watch } from 'vue'
import MarkdownIt from 'markdown-it'
import type { UIMessage, TextPart, ThinkingPart, ToolCallPart, ToolResultPart } from '@tanstack/ai/client'

const props = defineProps<{
  messages: UIMessage[]
  isLoading: boolean
}>()

const containerRef = ref<HTMLDivElement | null>(null)
const userScrolledUp = ref(false)
const hasNewWhileAway = ref(false)
let lastMessageCount = 0

const md = new MarkdownIt({ html: false, linkify: true, breaks: false })

function onScroll() {
  const el = containerRef.value
  if (!el) return
  const away = el.scrollHeight - el.scrollTop - el.clientHeight > 80
  userScrolledUp.value = away
  if (!away) hasNewWhileAway.value = false
}

function scrollToBottom(smooth = true) {
  const el = containerRef.value
  if (!el) return
  el.scrollTo({ top: el.scrollHeight, behavior: smooth ? 'smooth' : 'auto' })
  hasNewWhileAway.value = false
}

watch(
  () => [props.messages, props.isLoading],
  async () => {
    const count = props.messages.length
    const grew = count > lastMessageCount
    lastMessageCount = count
    const lastMsg = props.messages[props.messages.length - 1]
    if (lastMsg?.role === 'user') {
      userScrolledUp.value = false
      hasNewWhileAway.value = false
    } else if (grew && userScrolledUp.value) {
      hasNewWhileAway.value = true
    }
    await nextTick()
    if (!userScrolledUp.value) {
      const el = containerRef.value
      if (el) el.scrollTop = el.scrollHeight
    }
  },
  { deep: true, immediate: true },
)

function textPartsOf(msg: UIMessage): TextPart[] {
  return msg.parts.filter((p) => p.type === 'text') as TextPart[]
}

function fullTextOf(msg: UIMessage): string {
  return textPartsOf(msg).map((p) => p.content).join('\n\n')
}

function renderMd(content: string): string {
  return md.render(content)
}

const copiedIds = ref<Set<string>>(new Set())

function handleCopy(msg: UIMessage) {
  navigator.clipboard.writeText(fullTextOf(msg)).then(() => {
    const s = new Set(copiedIds.value)
    s.add(msg.id)
    copiedIds.value = s
    setTimeout(() => {
      const s2 = new Set(copiedIds.value)
      s2.delete(msg.id)
      copiedIds.value = s2
    }, 2000)
  })
}

const thinkingOpen = ref<Record<string, boolean>>({})
function toggleThinking(key: string) {
  thinkingOpen.value = { ...thinkingOpen.value, [key]: !thinkingOpen.value[key] }
}

function asText(p: unknown): TextPart { return p as TextPart }
function asThinking(p: unknown): ThinkingPart { return p as ThinkingPart }
function asToolCall(p: unknown): ToolCallPart { return p as ToolCallPart }
function asToolResult(p: unknown): ToolResultPart { return p as ToolResultPart }
</script>

<template>
  <div class="relative flex-1 flex flex-col overflow-hidden">
  <div
    ref="containerRef"
    class="flex-1 overflow-y-auto bg-[var(--bg-canvas)]"
    @scroll="onScroll"
  >
    <div class="max-w-[760px] mx-auto px-[var(--spacing-6)] pt-[var(--spacing-8)] pb-[var(--spacing-4)] flex flex-col">
      <div v-for="msg in messages" :key="msg.id" class="mb-[var(--spacing-7)]">
        <!-- User -->
        <div v-if="msg.role === 'user'" class="flex justify-end">
          <div
            class="ml-auto max-w-[80%] bg-[var(--bg-contrast)] text-[var(--bg-canvas)] rounded-[var(--shape-card)] px-[var(--spacing-4)] py-[var(--spacing-2)] text-body-md whitespace-pre-wrap break-words"
            style="line-height: 1.6;"
          >
            <span v-for="(p, i) in textPartsOf(msg)" :key="i">{{ p.content }}</span>
          </div>
        </div>

        <!-- Assistant -->
        <div v-else class="msg-assistant flex flex-col">
          <div class="flex items-start gap-[var(--spacing-3)] mb-[var(--spacing-3)]">
            <div
              class="w-8 h-8 rounded-[var(--shape-elements)] bg-[var(--bg-surface)] flex items-center justify-center flex-shrink-0"
            >
              <svg width="16" height="16" viewBox="0 0 21 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M18.2868 0L0.490892 14.9821L0 17.561H2.5639L16.349 5.96141L14.1271 17.561H17.4898L20.8537 0H18.2868Z" fill="currentColor" style="color: var(--primary);" />
              </svg>
            </div>
            <div class="flex flex-col min-w-0">
              <div class="text-body-md font-medium text-[var(--text-default)]" style="line-height: 1.2;">
                Azion Copilot
              </div>
              <div class="text-body-xs text-[var(--text-muted)]" style="line-height: 1.2;">
                Response ready
              </div>
            </div>
          </div>
          <div class="msg-assistant-content flex-1 min-w-0">
            <template v-for="(part, i) in msg.parts" :key="i">
              <!-- text -->
              <div
                v-if="part.type === 'text'"
                class="prose-azion"
                v-html="renderMd(asText(part).content)"
              />
              <!-- thinking -->
              <div v-else-if="part.type === 'thinking'" class="mb-[var(--spacing-2)]">
                <button
                  class="flex items-center gap-[var(--spacing-1)] bg-transparent border-0 cursor-pointer py-[var(--spacing-1)] text-[var(--text-muted)] text-body-xxs font-mono tracking-wider uppercase"
                  @click="toggleThinking(`${msg.id}-${i}`)"
                >
                  <span class="text-body-xxs">{{ thinkingOpen[`${msg.id}-${i}`] ? '▼' : '▶' }}</span>
                  Thinking
                </button>
                <div
                  v-if="thinkingOpen[`${msg.id}-${i}`]"
                  class="mt-[var(--spacing-1)] px-[var(--spacing-3)] py-[var(--spacing-2)] bg-[var(--bg-hover)] border border-[var(--border-muted)] rounded-[var(--shape-elements)] text-body-sm text-[var(--text-muted)] font-mono whitespace-pre-wrap break-words"
                  style="line-height: 1.6;"
                >
                  {{ asThinking(part).content }}
                </div>
              </div>
              <!-- tool-call -->
              <div
                v-else-if="part.type === 'tool-call'"
                class="inline-flex items-center gap-[var(--spacing-1)] px-[var(--spacing-2)] py-[var(--spacing-1)] bg-[var(--info-mask,var(--bg-hover))] border border-[var(--info-border)] rounded-[var(--shape-elements)] mb-[var(--spacing-1)] text-body-xxs font-mono text-[var(--info)] tracking-wide"
              >
                <span class="opacity-60">⚙</span>
                {{ asToolCall(part).name }}
              </div>
              <!-- tool-result -->
              <div
                v-else-if="part.type === 'tool-result'"
                class="inline-flex items-center gap-[var(--spacing-1)] px-[var(--spacing-2)] py-[var(--spacing-1)] rounded-[var(--shape-elements)] mb-[var(--spacing-1)] text-body-xxs font-mono tracking-wide border"
                :class="asToolResult(part).state === 'error'
                  ? 'bg-[var(--bg-hover)] border-[var(--danger-border)] text-[var(--danger)]'
                  : 'bg-[var(--bg-hover)] border-[var(--success-border)] text-[var(--success)]'"
              >
                <span class="opacity-60">{{ asToolResult(part).state === 'error' ? '✗' : '✓' }}</span>
                Result
              </div>
            </template>

            <button
              v-if="fullTextOf(msg)"
              :title="copiedIds.has(msg.id) ? 'Copiado!' : 'Copiar'"
              :class="copiedIds.has(msg.id) ? 'copy-btn copy-btn--done' : 'copy-btn'"
              class="flex items-center gap-[var(--spacing-1)] mt-[var(--spacing-1)] bg-transparent border-0 cursor-pointer py-[var(--spacing-1)] text-body-xxs font-mono tracking-wide"
              @click="handleCopy(msg)"
            >
              <svg v-if="copiedIds.has(msg.id)" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="20 6 9 17 4 12" />
              </svg>
              <svg v-else width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <rect x="9" y="9" width="13" height="13" rx="2" />
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
              </svg>
              {{ copiedIds.has(msg.id) ? 'Copiado' : 'Copiar' }}
            </button>
          </div>
        </div>
      </div>

      <!-- Streaming indicator -->
      <div v-if="isLoading" class="flex gap-[var(--spacing-3)] items-start mb-[var(--spacing-7)]">
        <div
          class="w-8 h-8 rounded-[var(--shape-elements)] bg-[var(--bg-surface)] flex items-center justify-center flex-shrink-0"
        >
          <svg width="16" height="16" viewBox="0 0 21 18" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M18.2868 0L0.490892 14.9821L0 17.561H2.5639L16.349 5.96141L14.1271 17.561H17.4898L20.8537 0H18.2868Z" fill="currentColor" style="color: var(--primary);" />
          </svg>
        </div>
        <div class="flex gap-[var(--spacing-1)] items-center pt-[var(--spacing-1)]">
          <span
            v-for="delay in [0, 150, 300]"
            :key="delay"
            class="w-[5px] h-[5px] rounded-full bg-[var(--primary)] inline-block"
            :style="{ animation: `azion-pulse 1.2s ease-in-out ${delay}ms infinite` }"
          />
        </div>
      </div>
    </div>
  </div>

    <Transition name="fade-up">
      <button
        v-if="userScrolledUp"
        type="button"
        :title="hasNewWhileAway ? 'Nova mensagem' : 'Voltar ao fim'"
        class="absolute bottom-[var(--spacing-4)] left-1/2 -translate-x-1/2 inline-flex items-center gap-[var(--spacing-2)] bg-[var(--bg-surface-raised)] border border-[var(--border-muted)] text-[var(--text-default)] text-body-xs rounded-full px-[var(--spacing-3)] py-[var(--spacing-2)] shadow-[var(--shadow-md)] cursor-pointer transition-colors hover:bg-[var(--bg-hover)]"
        @click="scrollToBottom()"
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <polyline points="6 9 12 15 18 9" />
        </svg>
        <span v-if="hasNewWhileAway">Nova mensagem</span>
      </button>
    </Transition>
  </div>
</template>

<style>
@keyframes azion-pulse {
  0%, 80%, 100% { opacity: 0.2; transform: scale(0.8); }
  40% { opacity: 1; transform: scale(1); }
}
.fade-up-enter-active,
.fade-up-leave-active {
  transition: opacity 180ms ease, transform 180ms ease;
}
.fade-up-enter-from,
.fade-up-leave-to {
  opacity: 0;
  transform: translate(-50%, 8px);
}
.fade-up-enter-to,
.fade-up-leave-from {
  opacity: 1;
  transform: translate(-50%, 0);
}
.msg-assistant-content,
.msg-assistant-content * {
  -webkit-user-select: text !important;
  user-select: text !important;
}
.msg-assistant-content button {
  -webkit-user-select: none !important;
  user-select: none !important;
  cursor: pointer;
}
.copy-btn {
  color: var(--text-muted);
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.15s ease, color 0.15s ease;
}
.msg-assistant:hover .copy-btn {
  opacity: 1;
  pointer-events: auto;
}
.copy-btn--done {
  color: var(--primary) !important;
  opacity: 1 !important;
  pointer-events: auto !important;
}
.copy-btn:hover {
  color: var(--text-default) !important;
}

/* Markdown styling for .prose-azion */
.prose-azion p {
  margin: 0 0 var(--spacing-3);
  color: var(--text-default);
  line-height: 1.7;
}
.prose-azion h1 {
  font-weight: 600;
  color: var(--text-default);
  margin: var(--spacing-5) 0 var(--spacing-2);
}
.prose-azion h2 {
  font-weight: 600;
  color: var(--text-default);
  margin: var(--spacing-4) 0 var(--spacing-1);
}
.prose-azion h3 {
  font-weight: 600;
  color: var(--text-default);
  margin: var(--spacing-3) 0 var(--spacing-1);
}
.prose-azion ul,
.prose-azion ol {
  margin: var(--spacing-1) 0 var(--spacing-3);
  padding-left: var(--spacing-5);
  color: var(--text-default);
  line-height: 1.7;
}
.prose-azion li { margin-bottom: var(--spacing-1); }
.prose-azion blockquote {
  margin: var(--spacing-2) 0;
  padding-left: var(--spacing-3);
  border-left: 2px solid var(--primary);
  color: var(--text-muted);
  font-style: italic;
}
.prose-azion strong { font-weight: 600; color: var(--text-default); }
.prose-azion em { color: var(--text-default); }
.prose-azion a { color: var(--primary); text-decoration: none; }
.prose-azion hr {
  border: none;
  border-top: 1px solid var(--border-muted);
  margin: var(--spacing-3) 0;
}
.prose-azion pre {
  margin: var(--spacing-3) 0;
  padding: var(--spacing-3) var(--spacing-4);
  background: var(--bg-surface);
  border: 1px solid var(--border-muted);
  border-radius: var(--shape-elements);
  overflow-x: auto;
  font-family: monospace;
  line-height: 1.6;
  color: var(--text-default);
}
.prose-azion pre code {
  background: transparent;
  border: none;
  padding: 0;
  color: var(--text-default);
}
.prose-azion code {
  font-family: monospace;
  font-size: 0.88em;
  background: var(--primary-mask);
  border: 1px solid var(--primary);
  border-radius: var(--shape-flat);
  padding: 1px var(--spacing-1);
  color: var(--primary-contrast);
}
</style>

// templates/react/tanstack-chat-ai/src/components/MessageList.tsx
import { useEffect, useRef, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import type { UIMessage, TextPart, ThinkingPart, ToolCallPart, ToolResultPart } from '@tanstack/ai/client'

interface Props {
  messages: UIMessage[]
  isLoading: boolean
}

export function MessageList({ messages, isLoading }: Props) {
  const containerRef = useRef<HTMLDivElement>(null)
  const userScrolledUp = useRef(false)

  function onScroll() {
    const el = containerRef.current
    if (!el) return
    userScrolledUp.current = el.scrollHeight - el.scrollTop - el.clientHeight > 80
  }

  useEffect(() => {
    const lastMsg = messages[messages.length - 1]
    if (lastMsg?.role === 'user') userScrolledUp.current = false
    if (!userScrolledUp.current) {
      const el = containerRef.current
      if (el) el.scrollTop = el.scrollHeight
    }
  }, [messages, isLoading])

  return (
    <div
      ref={containerRef}
      onScroll={onScroll}
      style={{ flex: 1, overflowY: 'auto', background: '#111111' }}
    >
      <div
        style={{
          maxWidth: '760px',
          margin: '0 auto',
          padding: '32px 24px 16px',
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        {messages.map((msg) => (
          <div key={msg.id} style={{ marginBottom: '28px' }}>
            {msg.role === 'user' ? (
              /* User message — right-aligned bubble */
              <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                <div
                  style={{
                    maxWidth: '72%',
                    background: 'rgba(254,96,31,0.12)',
                    border: '0.8px solid rgba(254,96,31,0.24)',
                    borderRadius: '18px 18px 4px 18px',
                    padding: '12px 16px',
                    color: '#FFB180',
                    fontSize: '15px',
                    lineHeight: '1.6',
                    whiteSpace: 'pre-wrap',
                    wordBreak: 'break-word',
                    fontFamily: "'Sora', sans-serif",
                  }}
                >
                  {msg.parts
                    .filter((p) => p.type === 'text')
                    .map((p, i) => (
                      <span key={i}>{(p as TextPart).content}</span>
                    ))}
                </div>
              </div>
            ) : (
              /* Assistant message — left-aligned, no bubble, with icon */
              <AssistantMessage msg={msg} />
            )}
          </div>
        ))}

        {/* Streaming indicator */}
        {isLoading && (
          <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start', marginBottom: '28px' }}>
            <div
              style={{
                width: '26px',
                height: '26px',
                borderRadius: '6px',
                background: 'rgba(254,96,31,0.12)',
                border: '0.8px solid rgba(254,96,31,0.24)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0,
              }}
            >
              <AzionStarIcon />
            </div>
            <div style={{ display: 'flex', gap: '4px', alignItems: 'center', paddingTop: '4px' }}>
              {[0, 150, 300].map((delay) => (
                <span
                  key={delay}
                  style={{
                    width: '5px',
                    height: '5px',
                    borderRadius: '50%',
                    background: '#FE601F',
                    display: 'inline-block',
                    animation: `azion-pulse 1.2s ease-in-out ${delay}ms infinite`,
                  }}
                />
              ))}
            </div>
          </div>
        )}
      </div>

      <style>{`
        @keyframes azion-pulse {
          0%, 80%, 100% { opacity: 0.2; transform: scale(0.8); }
          40% { opacity: 1; transform: scale(1); }
        }
        .msg-assistant-content,
        .msg-assistant-content * {
          -webkit-user-select: text !important;
          user-select: text !important;
        }
        .msg-assistant-content button {
          -webkit-user-select: none !important;
          user-select: none !important;
          cursor: pointer;
        }
        .copy-btn {
          color: #4D4D4D;
          opacity: 0;
          pointer-events: none;
          transition: opacity 0.15s ease, color 0.15s ease;
        }
        .msg-assistant:hover .copy-btn {
          opacity: 1;
          pointer-events: auto;
        }
        .copy-btn--done {
          color: #FE601F !important;
          opacity: 1 !important;
          pointer-events: auto !important;
        }
        .copy-btn:hover {
          color: #FCFCFC !important;
        }
      `}</style>
    </div>
  )
}

function AssistantMessage({ msg }: { msg: UIMessage }) {
  const [copied, setCopied] = useState(false)

  const fullText = msg.parts
    .filter((p) => p.type === 'text')
    .map((p) => (p as TextPart).content)
    .join('\n\n')

  function handleCopy() {
    navigator.clipboard.writeText(fullText).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  return (
    <div className="msg-assistant" style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
      <div
        style={{
          width: '26px',
          height: '26px',
          borderRadius: '6px',
          background: 'rgba(254,96,31,0.12)',
          border: '0.8px solid rgba(254,96,31,0.24)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexShrink: 0,
          marginTop: '1px',
        }}
      >
        <AzionStarIcon />
      </div>
      <div className="msg-assistant-content" style={{ flex: 1, minWidth: 0 }}>
        {msg.parts.map((part, i) => {
          if (part.type === 'text')
            return <TextRenderer key={i} part={part as TextPart} />
          if (part.type === 'thinking')
            return <ThinkingRenderer key={i} part={part as ThinkingPart} />
          if (part.type === 'tool-call')
            return <ToolCallRenderer key={i} part={part as ToolCallPart} />
          if (part.type === 'tool-result')
            return <ToolResultRenderer key={i} part={part as ToolResultPart} />
          return null
        })}
        {fullText && (
          <button
            onClick={handleCopy}
            title={copied ? 'Copiado!' : 'Copiar'}
            className={copied ? 'copy-btn copy-btn--done' : 'copy-btn'}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '5px',
              marginTop: '6px',
              background: 'transparent',
              border: 'none',
              cursor: 'pointer',
              padding: '4px 0',
              fontSize: '11px',
              fontFamily: 'monospace',
              letterSpacing: '0.04em',
            }}
          >
            {copied ? <CheckIcon /> : <CopyIcon />}
            {copied ? 'Copiado' : 'Copiar'}
          </button>
        )}
      </div>
    </div>
  )
}

function TextRenderer({ part }: { part: TextPart }) {
  return (
    <div className="prose-azion">
      <ReactMarkdown
        components={{
          p: ({ children }) => (
            <p style={{ margin: '0 0 12px', color: '#E5E5E5', fontSize: '15px', lineHeight: '1.7', fontFamily: "'Sora', sans-serif" }}>
              {children}
            </p>
          ),
          code: ({ children, className }) => {
            const isBlock = className?.startsWith('language-')
            const lang = className?.replace('language-', '') ?? ''
            if (isBlock) {
              return (
                <div style={{ margin: '12px 0' }}>
                  {lang && (
                    <div
                      style={{
                        padding: '4px 12px',
                        background: '#1A1A1A',
                        borderRadius: '4px 4px 0 0',
                        borderTop: '0.8px solid rgba(255,255,255,0.08)',
                        borderLeft: '0.8px solid rgba(255,255,255,0.08)',
                        borderRight: '0.8px solid rgba(255,255,255,0.08)',
                        fontFamily: 'monospace',
                        fontSize: '10px',
                        color: '#666666',
                        letterSpacing: '0.06em',
                        textTransform: 'uppercase',
                      }}
                    >
                      {lang}
                    </div>
                  )}
                  <pre
                    style={{
                      margin: 0,
                      padding: '14px 16px',
                      background: '#0D0D0D',
                      border: '0.8px solid rgba(255,255,255,0.08)',
                      borderRadius: lang ? '0 0 4px 4px' : '4px',
                      overflowX: 'auto',
                      fontFamily: 'monospace',
                      fontSize: '13px',
                      lineHeight: '1.6',
                      color: '#FCFCFC',
                    }}
                  >
                    <code>{children}</code>
                  </pre>
                </div>
              )
            }
            return (
              <code
                style={{
                  fontFamily: 'monospace',
                  fontSize: '0.88em',
                  background: 'rgba(254,96,31,0.08)',
                  border: '0.8px solid rgba(254,96,31,0.16)',
                  borderRadius: '3px',
                  padding: '1px 5px',
                  color: '#FF8E4D',
                }}
              >
                {children}
              </code>
            )
          },
          pre: ({ children }) => <>{children}</>,
          h1: ({ children }) => (
            <h1 style={{ fontSize: '20px', fontWeight: 600, color: '#FCFCFC', margin: '20px 0 8px', fontFamily: "'Sora', sans-serif" }}>
              {children}
            </h1>
          ),
          h2: ({ children }) => (
            <h2 style={{ fontSize: '17px', fontWeight: 600, color: '#FCFCFC', margin: '16px 0 6px', fontFamily: "'Sora', sans-serif" }}>
              {children}
            </h2>
          ),
          h3: ({ children }) => (
            <h3 style={{ fontSize: '15px', fontWeight: 600, color: '#FCFCFC', margin: '12px 0 4px', fontFamily: "'Sora', sans-serif" }}>
              {children}
            </h3>
          ),
          ul: ({ children }) => (
            <ul style={{ margin: '4px 0 12px', paddingLeft: '20px', color: '#E5E5E5', fontSize: '15px', lineHeight: '1.7', fontFamily: "'Sora', sans-serif" }}>
              {children}
            </ul>
          ),
          ol: ({ children }) => (
            <ol style={{ margin: '4px 0 12px', paddingLeft: '20px', color: '#E5E5E5', fontSize: '15px', lineHeight: '1.7', fontFamily: "'Sora', sans-serif" }}>
              {children}
            </ol>
          ),
          li: ({ children }) => <li style={{ marginBottom: '4px' }}>{children}</li>,
          blockquote: ({ children }) => (
            <blockquote
              style={{
                margin: '8px 0',
                paddingLeft: '12px',
                borderLeft: '2px solid rgba(254,96,31,0.4)',
                color: '#999999',
                fontStyle: 'italic',
              }}
            >
              {children}
            </blockquote>
          ),
          strong: ({ children }) => <strong style={{ fontWeight: 600, color: '#FCFCFC' }}>{children}</strong>,
          em: ({ children }) => <em style={{ color: '#B2B2B2' }}>{children}</em>,
          a: ({ href, children }) => (
            <a href={href} target="_blank" rel="noopener noreferrer" style={{ color: '#FE601F', textDecoration: 'none' }}>
              {children}
            </a>
          ),
          hr: () => <hr style={{ border: 'none', borderTop: '0.8px solid rgba(255,255,255,0.08)', margin: '12px 0' }} />,
        }}
      >
        {part.content}
      </ReactMarkdown>
    </div>
  )
}

function ThinkingRenderer({ part }: { part: ThinkingPart }) {
  const [open, setOpen] = useState(false)
  return (
    <div style={{ marginBottom: '8px' }}>
      <button
        onClick={() => setOpen((v) => !v)}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '6px',
          background: 'transparent',
          border: 'none',
          cursor: 'pointer',
          padding: '4px 0',
          color: '#4D4D4D',
          fontSize: '11px',
          fontFamily: 'monospace',
          letterSpacing: '0.06em',
          textTransform: 'uppercase',
        }}
      >
        <span style={{ fontSize: '8px' }}>{open ? '▼' : '▶'}</span>
        Thinking
      </button>
      {open && (
        <div
          style={{
            marginTop: '6px',
            padding: '10px 14px',
            background: 'rgba(255,255,255,0.02)',
            border: '0.8px solid rgba(255,255,255,0.06)',
            borderRadius: '4px',
            fontSize: '13px',
            color: '#4D4D4D',
            fontFamily: 'monospace',
            lineHeight: '1.6',
            whiteSpace: 'pre-wrap',
            wordBreak: 'break-word',
          }}
        >
          {part.content}
        </div>
      )}
    </div>
  )
}

function ToolCallRenderer({ part }: { part: ToolCallPart }) {
  return (
    <div
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        padding: '4px 10px',
        background: 'rgba(138,132,236,0.08)',
        border: '0.8px solid rgba(138,132,236,0.2)',
        borderRadius: '4px',
        marginBottom: '6px',
        fontSize: '11px',
        fontFamily: 'monospace',
        color: '#8A84EC',
        letterSpacing: '0.04em',
      }}
    >
      <span style={{ opacity: 0.6 }}>⚙</span>
      {part.name}
    </div>
  )
}

function ToolResultRenderer({ part }: { part: ToolResultPart }) {
  return (
    <div
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        padding: '4px 10px',
        background: part.state === 'error' ? 'rgba(255,77,77,0.08)' : 'rgba(38,217,104,0.08)',
        border: `0.8px solid ${part.state === 'error' ? 'rgba(255,77,77,0.2)' : 'rgba(38,217,104,0.2)'}`,
        borderRadius: '4px',
        marginBottom: '6px',
        fontSize: '11px',
        fontFamily: 'monospace',
        color: part.state === 'error' ? '#FF4D4D' : '#26D968',
        letterSpacing: '0.04em',
      }}
    >
      <span style={{ opacity: 0.6 }}>{part.state === 'error' ? '✗' : '✓'}</span>
      Result
    </div>
  )
}

function AzionStarIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 20 20" fill="none">
      <path
        d="M10 2L12.4 7.6L18 8.2L14 12.4L15.2 18L10 15.2L4.8 18L6 12.4L2 8.2L7.6 7.6L10 2Z"
        stroke="#FE601F"
        strokeWidth="1.5"
        strokeLinejoin="round"
      />
    </svg>
  )
}

function CopyIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect x="9" y="9" width="13" height="13" rx="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  )
}

function CheckIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}
